### ISSUE TITLE
Can't start the example app

### ISSUE THREAD

**Issue by visibletrap** [domino-clj/examples#1]
<img width="975" alt="Screen Shot 2019-11-04 at 04 24 38" src="https://user-images.githubusercontent.com/625523/68092195-38fdb000-febb-11e9-933e-c905703e3e49.png">

**Comment by yogthos** [comment]
Thanks, I missed a nil check passing the number to google string formatter, [fixed here](https://github.com/domino-clj/examples/commit/2a8fc312006fd08e0c8a0e43196a98051652adfc).

**Comment by visibletrap** [comment]
Thanks.
